# Generated by Django 5.2.3 on 2025-08-01 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='intervention',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='intervention',
            name='problem_type',
            field=models.CharField(blank=True, help_text='Type of problem (e.g., Technical, Billing, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='intervention',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('client_message', 'Client Message'), ('employee_message', 'Employee Message'), ('system_message', 'System Message')], default='client_message', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_client', 'Waiting for Client'), ('waiting_for_employee', 'Waiting for Employee'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
