# Generated by Django 5.2.4 on 2025-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_app', '0002_alter_message_options_intervention_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='chat_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='chat_ended_by_employee',
            field=models.BooleanField(default=False),
        ),
    ]
