# Generated by Django 5.2.3 on 2025-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_app', '0003_intervention_chat_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='chat_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
